# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.crudable:
        class: AppBundle\Service\CrudableService
        arguments: ['@doctrine.orm.entity_manager']
    app.file_manager:
        class: AppBundle\Service\FileManager
        arguments: ['@doctrine.orm.entity_manager']